### ISSUE TITLE
`encode': U+2019 to CP850 in conversion

### ISSUE THREAD

**Issue by DRAKUN** [lewagon/install-middleman#1]
c:\RubyDevKit>ruby dk.rb init
[INFO] found RubyInstaller v2.1.6 at C:/Ruby21
C:/Ruby21/lib/ruby/2.1.0/win32/registry.rb:178:in `encode': U+2019 to CP850 in conversion from UTF-16LE to UTF-8 to CP850 (Encoding::UndefinedConversionError)
        from C:/Ruby21/lib/ruby/2.1.0/win32/registry.rb:178:in`initialize'
        from C:/Ruby21/lib/ruby/2.1.0/win32/registry.rb:238:in `exception'
        from C:/Ruby21/lib/ruby/2.1.0/win32/registry.rb:238:in`raise'
        from C:/Ruby21/lib/ruby/2.1.0/win32/registry.rb:238:in `check'
        from C:/Ruby21/lib/ruby/2.1.0/win32/registry.rb:300:in`EnumKey'
        from C:/Ruby21/lib/ruby/2.1.0/win32/registry.rb:594:in `each_key'
        from dk.rb:116:in`block (2 levels) in scan_for'
        from C:/Ruby21/lib/ruby/2.1.0/win32/registry.rb:422:in `open'
        from C:/Ruby21/lib/ruby/2.1.0/win32/registry.rb:529:in`open'
        from dk.rb:115:in `block in scan_for'
        from dk.rb:113:in`each'
        from dk.rb:113:in `scan_for'
        from dk.rb:135:in`block in installed_rubies'
        from dk.rb:135:in `collect'
        from dk.rb:135:in`installed_rubies'
        from dk.rb:143:in `init'
        from dk.rb:310:in`run'
        from dk.rb:329:in `<main>'

**Comment by DRAKUN** [comment]
i resolve this :+1: 
To resolve this issue I manually modified line 70 of 
C:\Ruby21\lib\ruby\2.1.0\win32\registry.rb:
- LOCALE = Encoding.find(Encoding.locale_charmap)
- LOCALE = Encoding::UTF_8
- #LOCALE = Encoding.find(Encoding.locale_charmap)
  Is it possible to change locale_charmap without hacking registry.rb ? UTF-8 is maybe a better default value ?

Thanks,
Guillaume

source : https://bugs.ruby-lang.org/issues/10300
